/******************************************************************************
 * ╔═══════════════════════════════════════════════════════════════════════╗ *
 * ║                                                                       ║ *
 * ║   WARNING: AUTO-GENERATED FILE                                        ║ *
 * ║                                                                       ║ *
 * ║   This file is automatically generated by SAP Fiori tools and is      ║ *
 * ║   overwritten when you run the OPA test generator again.              ║ *
 * ║                                                                       ║ *
 * ║   To add your own custom tests:                                       ║ *
 * ║   - Create a new journey test file in this directory.                 ║ *
 * ║   - Follow the same pattern as this file.                             ║ *
 * ║   - Add the new file to the opaTests.qunit.js config file.            ║ *
 * ║   - Custom journey files are not overwritten.                         ║ *
 * ║                                                                       ║ *
 * ╚═══════════════════════════════════════════════════════════════════════╝ *
 ******************************************************************************/

sap.ui.define([
    "sap/ui/test/opaQunit",
    "./pages/JourneyRunner"
], function (opaTest, runner) {
    "use strict";

    function journey() {
        QUnit.module("ToursListListReport journey");

        opaTest("Start application", function (Given, When, Then) {
            Given.iStartMyApp();

            Then.onTheToursList.iSeeThisPage();
        });

        opaTest("Check filter bar", function (Given, When, Then) {
            Then.onTheToursList.onFilterBar().iCheckFilterField("tourCode");
            Then.onTheToursList.onFilterBar().iCheckFilterField("tourDate");
            Then.onTheToursList.onFilterBar().iCheckFilterField("zone");
            Then.onTheToursList.onFilterBar().iCheckFilterField("status");
        });

        opaTest("Check table columns and actions", function (Given, When, Then) {
            Then.onTheToursList.onTable().iCheckColumns(undefined, {"tourCode":{"header":"Code"},"tourDate":{"header":"Date"},"zone":{"header":"Zone"},"collectionType":{"header":"Type collecte"},"status":{"header":"Statut"},"client/name":{"header":"Client"},"vehicle/registrationNumber":{"header":"Véhicule"},"driver/firstName":{"header":"Chauffeur"}});

        });



        opaTest("Navigate to ObjectPage", function (Given, When, Then) {
            // Note: this test will fail if the ListReport page doesn't show any data
            
            When.onTheToursList.onFilterBar().iExecuteSearch();
            
            Then.onTheToursList.onTable().iCheckRows();

            When.onTheToursList.onTable().iPressRow(0);
            Then.onTheToursObjectPage.iSeeThisPage();

        });

        opaTest("Teardown", function (Given, When, Then) { 
            // Cleanup
            Given.iTearDownMyApp();
        });
    }

    runner.run([journey]);
});