/******************************************************************************
 * ╔═══════════════════════════════════════════════════════════════════════╗ *
 * ║                                                                       ║ *
 * ║   WARNING: AUTO-GENERATED FILE                                        ║ *
 * ║                                                                       ║ *
 * ║   This file is automatically generated by SAP Fiori tools and is      ║ *
 * ║   overwritten when you run the OPA test generator again.              ║ *
 * ║                                                                       ║ *
 * ║   To add your own custom tests:                                       ║ *
 * ║   - Create a new journey test file in this directory.                 ║ *
 * ║   - Follow the same pattern as this file.                             ║ *
 * ║   - Add the new file to the opaTests.qunit.js config file.            ║ *
 * ║   - Custom journey files are not overwritten.                         ║ *
 * ║                                                                       ║ *
 * ╚═══════════════════════════════════════════════════════════════════════╝ *
 ******************************************************************************/

sap.ui.define([
    "sap/ui/test/opaQunit",
    "./pages/JourneyRunner"
], function (opaTest, runner) {
    "use strict";

    function journey() {
        QUnit.module("ToursObjectPageObjectPage journey");

        opaTest("Navigate to ToursObjectPageObjectPage", function (Given, When, Then) {
            Given.iStartMyApp();

            When.onTheToursList.onFilterBar().iExecuteSearch();

            Then.onTheToursList.onTable().iCheckRows();
            When.onTheToursList.onTable().iPressRow(0);

            Then.onTheToursObjectPage.iSeeThisPage();
        });


        opaTest("Check body sections of the Object Page", function (Given, When, Then) {
            Then.onTheToursObjectPage.iCheckNumberOfSections(5);
            When.onTheToursObjectPage.iPressSectionIconTabFilterButton("FieldGroup::General");
            Then.onTheToursObjectPage.iCheckSection({ section: "FieldGroup::General" });
            Then.onTheToursObjectPage.onForm({ section: "FieldGroup::General" }).iCheckField({ property: "tourCode" });
            Then.onTheToursObjectPage.onForm({ section: "FieldGroup::General" }).iCheckField({ property: "tourDate" });
            Then.onTheToursObjectPage.onForm({ section: "FieldGroup::General" }).iCheckField({ property: "zone" });
            Then.onTheToursObjectPage.onForm({ section: "FieldGroup::General" }).iCheckField({ property: "collectionType" });
            Then.onTheToursObjectPage.onForm({ section: "FieldGroup::General" }).iCheckField({ property: "status" });
            Then.onTheToursObjectPage.onForm({ section: "FieldGroup::General" }).iCheckField({ property: "description" });
            Then.onTheToursObjectPage.onForm({ section: "FieldGroup::General" }).iCheckField({ property: "rejectionReason" });
            When.onTheToursObjectPage.iPressSectionIconTabFilterButton("client::LineItem");
            Then.onTheToursObjectPage.iCheckSection({ section: "client::LineItem" });
            When.onTheToursObjectPage.iPressSectionIconTabFilterButton("FieldGroup::Resources");
            Then.onTheToursObjectPage.iCheckSection({ section: "FieldGroup::Resources" });
            Then.onTheToursObjectPage.onForm({ section: "FieldGroup::Resources" }).iCheckField({ property: "vehicle/registrationNumber" });
            Then.onTheToursObjectPage.onForm({ section: "FieldGroup::Resources" }).iCheckField({ property: "vehicle/type" });
            Then.onTheToursObjectPage.onForm({ section: "FieldGroup::Resources" }).iCheckField({ property: "driver/firstName" });
            Then.onTheToursObjectPage.onForm({ section: "FieldGroup::Resources" }).iCheckField({ property: "driver/lastName" });
            When.onTheToursObjectPage.iPressSectionIconTabFilterButton("roadmap::LineItem");
            Then.onTheToursObjectPage.iCheckSection({ section: "roadmap::LineItem" });
            When.onTheToursObjectPage.iPressSectionIconTabFilterButton("decisions::LineItem");
            Then.onTheToursObjectPage.iCheckSection({ section: "decisions::LineItem" });
       });

        opaTest("Teardown", function (Given, When, Then) { 
            // Cleanup
            Given.iTearDownMyApp();
        });
    }

    runner.run([journey]);
});