/******************************************************************************
 * ╔═══════════════════════════════════════════════════════════════════════╗ *
 * ║                                                                       ║ *
 * ║   WARNING: AUTO-GENERATED FILE                                        ║ *
 * ║                                                                       ║ *
 * ║   This file is automatically generated by SAP Fiori tools and is      ║ *
 * ║   overwritten when you run the OPA test generator again.              ║ *
 * ║                                                                       ║ *
 * ║   To add your own custom tests:                                       ║ *
 * ║   - Create a new journey test file in this directory.                 ║ *
 * ║   - Follow the same pattern as this file.                             ║ *
 * ║   - Add the new file to the opaTests.qunit.js config file.            ║ *
 * ║   - Custom journey files are not overwritten.                         ║ *
 * ║                                                                       ║ *
 * ╚═══════════════════════════════════════════════════════════════════════╝ *
 ******************************************************************************/

sap.ui.define([
    "sap/ui/test/opaQunit",
    "./pages/JourneyRunner"
], function (opaTest, runner) {
    "use strict";

    function journey() {
        QUnit.module("RoadmapsObjectPageObjectPage journey");

        opaTest("Navigate to RoadmapsObjectPageObjectPage", function (Given, When, Then) {
            Given.iStartMyApp();

            When.onTheRoadmapsList.onFilterBar().iExecuteSearch();

            Then.onTheRoadmapsList.onTable().iCheckRows();
            When.onTheRoadmapsList.onTable().iPressRow(0);

            Then.onTheRoadmapsObjectPage.iSeeThisPage();
        });


        opaTest("Check body sections of the Object Page", function (Given, When, Then) {
            Then.onTheRoadmapsObjectPage.iCheckNumberOfSections(3);
            When.onTheRoadmapsObjectPage.iPressSectionIconTabFilterButton("FieldGroup::RoadmapGeneral");
            Then.onTheRoadmapsObjectPage.iCheckSection({ section: "FieldGroup::RoadmapGeneral" });
            Then.onTheRoadmapsObjectPage.onForm({ section: "FieldGroup::RoadmapGeneral" }).iCheckField({ property: "roadmapCode" });
            Then.onTheRoadmapsObjectPage.onForm({ section: "FieldGroup::RoadmapGeneral" }).iCheckField({ property: "startDate" });
            Then.onTheRoadmapsObjectPage.onForm({ section: "FieldGroup::RoadmapGeneral" }).iCheckField({ property: "endDate" });
            Then.onTheRoadmapsObjectPage.onForm({ section: "FieldGroup::RoadmapGeneral" }).iCheckField({ property: "status" });
            When.onTheRoadmapsObjectPage.iPressSectionIconTabFilterButton("FieldGroup::RoadmapTour");
            Then.onTheRoadmapsObjectPage.iCheckSection({ section: "FieldGroup::RoadmapTour" });
            Then.onTheRoadmapsObjectPage.onForm({ section: "FieldGroup::RoadmapTour" }).iCheckField({ property: "tourCode" });
            Then.onTheRoadmapsObjectPage.onForm({ section: "FieldGroup::RoadmapTour" }).iCheckField({ property: "tourDate" });
            Then.onTheRoadmapsObjectPage.onForm({ section: "FieldGroup::RoadmapTour" }).iCheckField({ property: "tourZone" });
            When.onTheRoadmapsObjectPage.iPressSectionIconTabFilterButton("FieldGroup::RoadmapTracking");
            Then.onTheRoadmapsObjectPage.iCheckSection({ section: "FieldGroup::RoadmapTracking" });
            Then.onTheRoadmapsObjectPage.onForm({ section: "FieldGroup::RoadmapTracking" }).iCheckField({ property: "rejectionReason" });
            Then.onTheRoadmapsObjectPage.onForm({ section: "FieldGroup::RoadmapTracking" }).iCheckField({ property: "createdAt" });
            Then.onTheRoadmapsObjectPage.onForm({ section: "FieldGroup::RoadmapTracking" }).iCheckField({ property: "updatedAt" });
       });

        opaTest("Teardown", function (Given, When, Then) { 
            // Cleanup
            Given.iTearDownMyApp();
        });
    }

    runner.run([journey]);
});