/******************************************************************************
 * ╔═══════════════════════════════════════════════════════════════════════╗ *
 * ║                                                                       ║ *
 * ║   WARNING: AUTO-GENERATED FILE                                        ║ *
 * ║                                                                       ║ *
 * ║   This file is automatically generated by SAP Fiori tools and is      ║ *
 * ║   overwritten when you run the OPA test generator again.              ║ *
 * ║                                                                       ║ *
 * ║   To add your own custom tests:                                       ║ *
 * ║   - Create a new journey test file in this directory.                 ║ *
 * ║   - Follow the same pattern as this file.                             ║ *
 * ║   - Add the new file to the opaTests.qunit.js config file.            ║ *
 * ║   - Custom journey files are not overwritten.                         ║ *
 * ║                                                                       ║ *
 * ╚═══════════════════════════════════════════════════════════════════════╝ *
 ******************************************************************************/

sap.ui.define([
    "sap/ui/test/opaQunit",
    "./pages/JourneyRunner"
], function (opaTest, runner) {
    "use strict";

    function journey() {
        QUnit.module("RoadmapsListListReport journey");

        opaTest("Start application", function (Given, When, Then) {
            Given.iStartMyApp();

            Then.onTheRoadmapsList.iSeeThisPage();
        });

        opaTest("Check filter bar", function (Given, When, Then) {
            Then.onTheRoadmapsList.onFilterBar().iCheckFilterField("Statut de modification");
            Then.onTheRoadmapsList.onFilterBar().iCheckFilterField("N° roadmap");
            Then.onTheRoadmapsList.onFilterBar().iCheckFilterField("Date début");
            Then.onTheRoadmapsList.onFilterBar().iCheckFilterField("Date fin");
            Then.onTheRoadmapsList.onFilterBar().iCheckFilterField("Tournée liée");
            Then.onTheRoadmapsList.onFilterBar().iCheckFilterField("Date tournée");
            Then.onTheRoadmapsList.onFilterBar().iCheckFilterField("Zone tournée");
        });

        opaTest("Check table columns and actions", function (Given, When, Then) {
            Then.onTheRoadmapsList.onTable().iCheckColumns(undefined, {"7":{"header":"Valider"},"8":{"header":"Rejeter"},"roadmapCode":{"header":"N° roadmap"},"tourCode":{"header":"Tournée liée"},"tourDate":{"header":"Date tournée"},"tourZone":{"header":"Zone"},"startDate":{"header":"Date début"},"endDate":{"header":"Date fin"},"status":{"header":"Statut"}});

        });



        opaTest("Navigate to ObjectPage", function (Given, When, Then) {
            // Note: this test will fail if the ListReport page doesn't show any data
            
            When.onTheRoadmapsList.onFilterBar().iExecuteSearch();
            
            Then.onTheRoadmapsList.onTable().iCheckRows();

            When.onTheRoadmapsList.onTable().iPressRow(0);
            Then.onTheRoadmapsObjectPage.iSeeThisPage();

        });

        opaTest("Teardown", function (Given, When, Then) { 
            // Cleanup
            Given.iTearDownMyApp();
        });
    }

    runner.run([journey]);
});